# Generated by Django 5.2.2 on 2025-06-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='order',
            name='current_event',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
