# Generated by Django 5.2.2 on 2025-06-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_event_order_current_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default='Unkown', max_length=250),
        ),
    ]
