# Generated by Django 3.2 on 2025-06-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_remove_order_productid_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=1, max_length=10),
        ),
    ]
